#!/usr/bin/env python
"""One-shot environment fixer so DeepSight can run *offline* inference/eval.

The repo ships an **incomplete** fork of `transformers` at
`src/transformers/src/transformers` (missing files such as `modeling_utils.py`,
`model_debugging_utils.py`, ...), so it cannot be imported on its own. The only
genuinely-patched module is the Qwen2.5-VL model (it adds the DINOv3 world head
`vis_head` + `dinov3` sub-model). Meanwhile the installed stock transformers
(>=4.56) already ships `models/dinov3_vit`. So the minimal, robust fix is to
**overlay just the patched `modeling_qwen2_5_vl.py` onto the complete installed
transformers** (a backup `*.orig` is kept).

It also fixes two things that otherwise crash model load:
  * `config.dinov3_config` in the published checkpoint points at a dead NAS path
    (`/mnt/nas-data-1/.../dinov3-vitL16/config.json`). We regenerate the correct
    DINOv3-ViT-L/16 config locally (from the spec in
    `dinov3_vit/convert_dinov3_vit_to_hf.py`) and repoint the checkpoint to it.

Idempotent: re-running is safe.

Usage:
    python scripts/setup_local_inference.py --ckpt ./checkpoints/deepsight
    python scripts/setup_local_inference.py --revert   # restore stock modeling file
"""
import argparse
import ast
import json
import os
import shutil
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORK_MODELING = os.path.join(
    REPO, "src", "transformers", "src", "transformers",
    "models", "qwen2_5_vl", "modeling_qwen2_5_vl.py",
)


def _global_qwen_dir() -> str:
    import transformers
    return os.path.join(os.path.dirname(transformers.__file__), "models", "qwen2_5_vl")


def overlay_modeling(revert: bool = False) -> None:
    gdir = _global_qwen_dir()
    target = os.path.join(gdir, "modeling_qwen2_5_vl.py")
    backup = target + ".orig"
    pycache = os.path.join(gdir, "__pycache__")

    if revert:
        if os.path.exists(backup):
            shutil.copy2(backup, target)
            shutil.rmtree(pycache, ignore_errors=True)
            print(f"[revert] restored stock modeling from {backup}")
        else:
            print("[revert] no backup found; nothing to do")
        return

    if not os.path.exists(FORK_MODELING):
        sys.exit(f"patched modeling not found: {FORK_MODELING}")

    # keep a one-time backup of the stock file
    if not os.path.exists(backup):
        shutil.copy2(target, backup)
        print(f"[overlay] backed up stock modeling -> {backup}")

    # Instead of COPYING the patched file, install a tiny SHIM that exec()s the
    # repo's modeling file, compiled with the REPO path as its filename. This makes
    # the repo file the live source: edits there take effect immediately, and
    # debugger breakpoints set in the repo file actually bind — because the executed
    # code objects carry the repo path (not this site-packages path) as co_filename.
    # Read the repo file and extract its public __all__ so transformers'
    # define_import_structure (which STATICALLY parses this on-disk file) still
    # discovers the exported classes — the exec() below supplies them at runtime.
    repo_src = open(FORK_MODELING, "r", encoding="utf-8").read()
    assert "vis_head" in repo_src and "dinov3" in repo_src, "repo modeling lacks DINOv3 head?!"
    all_names = None
    for node in ast.walk(ast.parse(repo_src)):
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
        ):
            all_names = list(ast.literal_eval(node.value))
    assert all_names, "could not find __all__ in repo modeling file"

    shim = (
        "# AUTO-GENERATED by scripts/setup_local_inference.py — do not edit.\n"
        "# Runs DeepSight's patched Qwen2.5-VL modeling code straight from the repo so\n"
        "# edits / debugger breakpoints in the repo file are live (executed code objects\n"
        "# carry the repo path as co_filename). The literal __all__ below keeps\n"
        "# transformers' static define_import_structure working; exec() supplies the code.\n"
        f"__all__ = {all_names!r}\n"
        f"_REPO_MODELING = {FORK_MODELING!r}\n"
        "with open(_REPO_MODELING, 'r', encoding='utf-8') as _f:\n"
        "    exec(compile(_f.read(), _REPO_MODELING, 'exec'), globals())\n"
        "del _f, _REPO_MODELING\n"
    )
    cur = open(target, "r", encoding="utf-8").read() if os.path.exists(target) else ""
    if cur == shim:
        print("[overlay] repo-linked shim already in place")
    else:
        with open(target, "w", encoding="utf-8") as f:
            f.write(shim)
        shutil.rmtree(pycache, ignore_errors=True)
        print(f"[overlay] installed repo-linked shim -> {target}")
        print(f"           (executes {FORK_MODELING})")


def write_dinov3_config(ckpt: str) -> str:
    """Regenerate the DINOv3-ViT-L/16 config the checkpoint expects."""
    from transformers.models.dinov3_vit import DINOv3ViTConfig

    # spec taken verbatim from dinov3_vit/convert_dinov3_vit_to_hf.py ("vitl16_lvd1689m")
    cfg = DINOv3ViTConfig(
        patch_size=16,
        hidden_size=1024,
        intermediate_size=4096,
        num_hidden_layers=24,
        num_attention_heads=16,
        num_register_tokens=4,
        use_gated_mlp=False,
        hidden_act="gelu",
    )
    out = os.path.join(os.path.abspath(ckpt), "dinov3_config.json")
    cfg.to_json_file(out)
    print(f"[dinov3] wrote ViT-L/16 config -> {out}")
    return out


def repoint_checkpoint(ckpt: str, dino_cfg_path: str) -> None:
    cfg_path = os.path.join(ckpt, "config.json")
    with open(cfg_path) as f:
        cfg = json.load(f)
    cfg["dinov3_config"] = dino_cfg_path
    if "text_config" in cfg:
        cfg["text_config"]["dinov3_config"] = dino_cfg_path
    with open(cfg_path, "w") as f:
        json.dump(cfg, f, indent=2)
    print(f"[checkpoint] repointed dinov3_config -> {dino_cfg_path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default=os.path.join(REPO, "checkpoints", "deepsight"))
    ap.add_argument("--revert", action="store_true")
    args = ap.parse_args()

    overlay_modeling(revert=args.revert)
    if args.revert:
        return

    if os.path.isdir(args.ckpt) and os.path.exists(os.path.join(args.ckpt, "config.json")):
        dino_cfg = write_dinov3_config(args.ckpt)
        repoint_checkpoint(args.ckpt, dino_cfg)
    else:
        print(f"[checkpoint] {args.ckpt} not ready yet (no config.json); "
              "re-run this script after the download finishes to fix dinov3_config")

    # Final import check in a FRESH interpreter — this process already imported
    # transformers before the shim was (re)written, so its module cache is stale;
    # a clean subprocess reflects the on-disk state the real run will see.
    import subprocess
    import textwrap
    code = textwrap.dedent(
        """
        import inspect
        from transformers import Qwen2_5_VLForConditionalGeneration as W  # top-level (as infer_local.py)
        from transformers.models.qwen2_5_vl.modeling_qwen2_5_vl import Qwen2_5_VLModel as M
        assert "dinov3" in inspect.getsource(W.__init__) and "vis_head" in inspect.getsource(W.__init__)
        print("[ok] patched Qwen2_5_VLForConditionalGeneration imports with the DINOv3 head")
        print("[ok] modeling executes from:", inspect.unwrap(M.forward).__code__.co_filename)
        print("     ^ set debugger breakpoints in THIS file")
        """
    )
    env = dict(os.environ, CUDA_VISIBLE_DEVICES="")
    if subprocess.run([sys.executable, "-c", code], env=env).returncode != 0:
        sys.exit("[error] post-install import check failed in a fresh interpreter")


if __name__ == "__main__":
    main()
